### ISSUE TITLE
Computer illiterate. How to use this to download a whole VK album?

### ISSUE THREAD

**Issue by aeon3** [Rast1234/VOffline#1]

**Comment by Rast1234** [comment]
Hello! I can make some examples for you this weekend and help along the way, but what do you call an "album"? Audio album, photo album? It would help if you give an VK link of what you expect to download.

**Comment by aeon3** [comment]
> Hello! I can make some examples for you this weekend and help along the way, but what do you call an "album"? Audio album, photo album? It would help if you give an VK link of what you expect to download.

Hi!!!

This is the album link:
https://vk.com/wall-111160014_33598

I need all those 136 pictures downloaded, preferably in order. Is that something I could achieve with your tool?

**Comment by Rast1234** [comment]
Yes. It will download all other albums along the way though, because it is made for massive backup scenarios. I will provide an example tomorrow.
As far as i know, there are other (more user-friendly) tools for this particular task, so try to search for them in meantime.

**Comment by Rast1234** [comment]
Here we go:

1. download the `build_windows.zip` from here: https://github.com/Rast1234/VOffline/releases/tag/0.1
2. unpack all files somewhere with plenty of free space
3. among all files, find `appsettings.json`, open with notepad and replace examples with your email and password, save
4. run `VOffline.exe` and wait for a looooong time since it will download all photo albums of that group, because this tool currently does not support downloading things one-by-one.
5. in the folder with all files, you will find new folder named as the community, for your case this is `G R A F I C A (111160014 - club111160014 - page)` with all downloaded stuff inside.

**Comment by Rast1234** [comment]
Nevermind, i just hacked it a bit and got just the album you need. See comments at the link you provided.
